
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassManagement
{

using System;
    using System.Collections.Generic;
    
public partial class ClassRooms
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ClassRooms()
    {

        this.Requests = new HashSet<Requests>();

    }


    public int ClassRoomId { get; set; }

    public int Number { get; set; }

    public int WorkPlacesCount { get; set; }

    public bool IsAvailable { get; set; }

    public string Description { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Requests> Requests { get; set; }

}

}
