

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassManagement
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class StepSchedulerEntities : DbContext
{
    public StepSchedulerEntities()
        : base("name=StepSchedulerEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ClassRooms> ClassRooms { get; set; }

    public virtual DbSet<Requests> Requests { get; set; }

    public virtual DbSet<ReservedRooms> ReservedRooms { get; set; }

    public virtual DbSet<Users> Users { get; set; }

}

}

