
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassManagement
{

using System;
    using System.Collections.Generic;
    
public partial class Requests
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Requests()
    {

        this.ReservedRooms = new HashSet<ReservedRooms>();

    }


    public int RequestId { get; set; }

    public int ClassRoomId { get; set; }

    public int UserId { get; set; }

    public System.DateTime DateRequest { get; set; }

    public System.DateTime ClassDate { get; set; }

    public int LessonNumber { get; set; }

    public int CountOfVisitors { get; set; }

    public string EventDescription { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<bool> IsNew { get; set; }



    public virtual ClassRooms ClassRooms { get; set; }

    public virtual Users Users { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ReservedRooms> ReservedRooms { get; set; }

}

}
