
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassManagement
{

using System;
    using System.Collections.Generic;
    
public partial class ReservedRooms
{

    public int ReservedRoomId { get; set; }

    public int RequestId { get; set; }

    public int EventType { get; set; }



    public virtual Requests Requests { get; set; }

}

}
