
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassManagement
{

using System;
    using System.Collections.Generic;
    
public partial class Users
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Users()
    {

        this.Requests = new HashSet<Requests>();

    }


    public int UserId { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public byte[] Photo { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string PhoneNumber { get; set; }

    public string E_Mail { get; set; }

    public Nullable<System.DateTime> BirthDate { get; set; }

    public string Description { get; set; }

    public Nullable<bool> IsAdmin { get; set; }

    public Nullable<bool> IsBlocked { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Requests> Requests { get; set; }

}

}
